### ISSUE TITLE
error message from R

### ISSUE THREAD

**Issue by egullive** [fwhelan/coinfinder-manuscript#1]
I am currently using coinfinder to detemine the co-occurance of genes in ~400 bacterial genomes. For the input i used the gene_presence_absence.csv file from roary and a tree generated from fastree using the core gene alignment from roary where I have removed the branch lengths as many of the branch lengths kept getting rounded to 0. When I ran coinfinder I recieved the following output;
coinfinder -I -i gene_presence_absence.csv -p treenobranch -o coinfinder_perfringens
Reading arguments...
> CORRECTION ······· = BONFERRONI
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = NO
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
> COMBINED_FILE ···· = gene_presence_absence.csv
> ALPHA_NAME ······· = Alpha
> BETA_NAME ········ = Beta
Formating Roary output for input into coinfinder...
Reading alpha-beta edges...
- n.ALPHA = 40938
- n.BETA  = 423
- n.GAMMA = 0
- n.EDGES = 1270801
Dropping saturated sets...
**Warning**: Saturated data has been dropped!
- d.ALPHA = -1
- n.ALPHA = 40937
- n.BETA  = 423
- n.GAMMA = 0
- n.EDGES = 1270801
Dropping rare elements in collection...
**Warning**: Rare elements have been dropped!
- d.ALPHA = -34969
- n.ALPHA = 5968
- n.BETA  = 423
- n.GAMMA = 0
- n.EDGES = 1270801
Dropping empty sets...
Nothing dropped, your data is good to go.
Iterating matrix...
Bonferroni significance correction, given 17811496 tests, the significance level has been reduced from 0.05 to 2.80718e-09.
Running analyses...
Calculating lineage dependence...
ERROR MESSAGE FROM R:
Error in p$edge.length[which(p$edge[, 2] == dd)] <- p$edge.length[which(p$edge[,  :
  replacement has length zero
Calls: midpoint.root -> reroot
Execution halted
 
I was wondering if anyone could help to explain why the execution was halted.

**Comment by fwhelan** [comment]
Hi egullive,

The package that `coinfinder` uses to determine the lineage dependence of coincident genes expects branch lengths to be present. If you're having trouble with zero length branches, I would suggest adjusting these to be very small lengths as opposed to removing them entirely.

Also, if you have any further issues could you please post them to the `coinfinder` repo (github.com/fwhelan/coinfinder) as opposed to this manuscript page.

Thanks,
Fiona
